require: rubocop-rails

AllCops:
 Exclude:
   - bin/*
   - db/**/*
   - test/**/*
   - tmp/**/*
   - vendor/**/*
Documentation:
 Enabled: false
Layout/ClassStructure:
 Enabled: true
Layout/SpaceBeforeFirstArg:
 Exclude:
   - app/views/api/**/**/*
Lint/AmbiguousBlockAssociation:
 Exclude:
   - spec/**/*
Metrics/AbcSize:
 # The ABC size is a calculated magnitude, so this number can be an Integer or
 # a Float.
 Max: 15
 Exclude:
Metrics/BlockLength:
 CountComments: false  # count full line comments?
 Max: 25
 Exclude:
   - app/admin/**/*
   - config/**/*
   - lib/tasks/auto_annotate_models.rake
   - spec/**/*
Metrics/BlockNesting:
 Max: 4
Metrics/ClassLength:
 CountComments: false  # count full line comments?
 Max: 200
# Avoid complex methods.
Metrics/CyclomaticComplexity:
 Max: 6
Metrics/MethodLength:
 CountComments: false  # count full line comments?
 Max: 24
Metrics/ModuleLength:
 CountComments: false  # count full line comments?
 Max: 200
Metrics/LineLength:
 Max: 100
 # To make it possible to copy or click on URIs in the code, we allow lines
 # containing a URI to be longer than Max.
 AllowURI: true
 Exclude:
  - config/initializers/backtrace_silencers.rb
  - config/initializers/devise.rb
 URISchemes:
   - http
   - https
Metrics/ParameterLists:
 Max: 5
 CountKeywordArgs: true
Metrics/PerceivedComplexity:
 Max: 12
Rails:
 Enabled: true
Rails/Delegate:
 Enabled: true
 Exclude:
  - app/controllers/concerns/act_as_api.rb
Rails/FilePath:
 Enabled: false
Rails/SaveBang:
 Enabled: true
Security/Open:
  Exclude:
    - app/models/user.rb
Style/BlockDelimiters:
 EnforcedStyle: braces_for_chaining
Style/ExpandPathArguments:
 Enabled: false
Style/FrozenStringLiteralComment:
 Enabled: false
Style/MixinUsage:
 Exclude:
   - spec/factories/user.rb
Style/ModuleFunction:
 Enabled: false
Style/ReturnNil:
 Enabled: true
